
spring: 
   datasource: 
      username: myadmin
      password: admin
      url: jdbc:mariadb://localhost:3306/mydb
      driverClassName: org.mariadb.jdbc.Driver
#   jpa:
#     hibernate.ddl-auto: create
#     show-sql: true
   jpa.properties.hibernate.format_sql: true

logging.level:
   org.hibernate:
      SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE
   com.chagvv: debug